# Generated by Django 5.2.7 on 2025-11-16 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('momentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='momento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='like',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='momentos.momento', verbose_name='Momento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='momentos.momento', verbose_name='Momento'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='momento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='momentos.momento', verbose_name='Momento relacionado'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Destino (Dono)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Origem (Ação)'),
        ),
        migrations.AddField(
            model_name='momento',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='momentos', to='momentos.tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('usuario', 'momento')},
        ),
    ]
