# Generated by Django 5.2.7 on 2025-12-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
