# Generated by Django 5.2.7 on 2025-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Perfil Privado'),
        ),
    ]
