# Generated by Django 5.2.7 on 2025-11-12 22:30

import momentos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagem de perfil (máximo 25MB)', null=True, upload_to='avatars/', validators=[momentos.validators.validate_avatar_size, momentos.validators.validate_avatar_format], verbose_name='Avatar'),
        ),
    ]
